name: doma-spring-boot-demo

on:
  push:
    paths:
    - 'src/**'
    - 'pom.xml'
    - '.github/**'

env:
  MAVEN_CLI_OPTS: -B -ntp -e

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: liberica
        java-version: 21
        cache: maven

    - name: Build with Maven
      run: mvn $MAVEN_CLI_OPTS test
